<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Gallery;
use Illuminate\Database\Seeder;

class GallerySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name'      => 'Jepang',
                'slug'      => 'jepang',
                'code'      => 'JP',
                'image'     => 'tours/thumbnails/01M2MK0Q45608Z5G4V6TF1MCX3.webp',
                'is_active' => true,
            ],
            [
                'name'      => 'Turki',
                'slug'      => 'turki',
                'code'      => 'TR',
                'image'     => 'tours/thumbnails/01M2MKEQ1FPWZ0JP3ZCJ24KZS2.webp',
                'is_active' => true,
            ],
            [
                'name'      => 'China',
                'slug'      => 'china',
                'code'      => 'CN',
                'image'     => 'tours/thumbnails/01M2MHG1Y5Z5MMB47W58DJBYWX.webp',
                'is_active' => true,
            ],
            [
                'name'      => 'Korea Selatan',
                'slug'      => 'korea-selatan',
                'code'      => 'KR',
                'image'     => 'tours/thumbnails/01M2MKQKC6YW3CHF8MEW7K4H7T.webp',
                'is_active' => true,
            ],
            [
                'name'      => 'Swiss',
                'slug'      => 'swiss',
                'code'      => 'CH',
                'image'     => 'banners/images/01M2JFKWDE8QBHTFEXA9N5F6V9.jpeg',
                'is_active' => true,
            ],
            [
                'name'      => 'Indonesia',
                'slug'      => 'indonesia',
                'code'      => 'ID',
                'image'     => 'banners/images/01M2JF85ZM9C7S43RKTA6PVHWT.jpeg',
                'is_active' => true,
            ],
            [
                'name'      => 'Prancis',
                'slug'      => 'prancis',
                'code'      => 'FR',
                'image'     => 'banners/images/01M2JFKWDE8QBHTFEXA9N5F6V9.jpeg',
                'is_active' => true,
            ],
            [
                'name'      => 'Yunani',
                'slug'      => 'yunani',
                'code'      => 'GR',
                'image'     => 'banners/images/01M2JF85ZM9C7S43RKTA6PVHWT.jpeg',
                'is_active' => true,
            ],
            [
                'name'      => 'Thailand',
                'slug'      => 'thailand',
                'code'      => 'TH',
                'image'     => 'tours/thumbnails/01M2MKQKC6YW3CHF8MEW7K4H7T.webp',
                'is_active' => true,
            ],
            [
                'name'      => 'Arab Saudi',
                'slug'      => 'arab-saudi',
                'code'      => 'SA',
                'image'     => 'banners/images/01M2J0A32Z4SVZYH1SCAJRF4XV.webp',
                'is_active' => true,
            ],
        ];

        foreach ($countries as $c) {
            Country::updateOrCreate(['name' => $c['name']], $c);
        }

        $galleries = [
            [
                'title'           => 'Momen Kehangatan Musim Gugur di Beijing & Tembok Besar',
                'category'        => 'China',
                'image_path'      => 'tours/thumbnails/01M2MHG1Y5Z5MMB47W58DJBYWX.webp',
                'destination'     => 'Beijing & Shanghai, China',
                'trip_date'       => 'Oktober 2026',
                'customer_name'   => 'Rombongan Bpk. Hendrawan & Keluarga',
                'customer_review' => 'Tour leader Super Vacation luar biasa sabar dan perhatian mengurus orang tua dan anak-anak kami. Pengalaman melihat Tembok Besar saat musim gugur sangat memukau!',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 1,
            ],
            [
                'title'           => 'Keindahan Gunung Fuji & Pesona Tokyo Golden Route',
                'category'        => 'Jepang',
                'image_path'      => 'tours/thumbnails/01M2MK0Q45608Z5G4V6TF1MCX3.webp',
                'destination'     => 'Tokyo & Kyoto, Jepang',
                'trip_date'       => 'September 2026',
                'customer_name'   => 'dr. Kevin Pratama & Rekan',
                'customer_review' => 'Jadwal itinerary sangat pas, tidak buru-buru, hotel berbintang di pusat kota dekat stasiun dan pusat perbelanjaan. Highly recommended!',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 2,
            ],
            [
                'title'           => 'Sensasi Terbang Balon Udara Saat Sunrise di Cappadocia',
                'category'        => 'Turki',
                'image_path'      => 'tours/thumbnails/01M2MKEQ1FPWZ0JP3ZCJ24KZS2.webp',
                'destination'     => 'Cappadocia & Istanbul, Turki',
                'trip_date'       => 'Agustus 2026',
                'customer_name'   => 'Keluarga Ibu Ratna Sari',
                'customer_review' => 'Mimpi naik balon udara Cappadocia akhirnya terwujud sempurna. Semua fasilitas hotel gua dan makanan halal terjamin 100%.',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 3,
            ],
            [
                'title'           => 'Romantisme Musim Gugur di Nami Island & Seoul City Tour',
                'category'        => 'Korea Selatan',
                'image_path'      => 'tours/thumbnails/01M2MKQKC6YW3CHF8MEW7K4H7T.webp',
                'destination'     => 'Seoul & Nami Island, Korea Selatan',
                'trip_date'       => 'Oktober 2026',
                'customer_name'   => 'Anindya Putri & Sahabat',
                'customer_review' => 'Spot foto yang dipilih tour guide sangat estetik dan instagrammable. Sangat menyenangkan liburan bareng sahabat tanpa pusing atur transportasi.',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 4,
            ],
            [
                'title'           => 'Eksplorasi Panorama Pegunungan Alpen & Keindahan Danau Swiss',
                'category'        => 'Swiss',
                'image_path'      => 'banners/images/01M2JFKWDE8QBHTFEXA9N5F6V9.jpeg',
                'destination'     => 'Zurich, Zermatt & Interlaken, Swiss',
                'trip_date'       => 'Juli 2026',
                'customer_name'   => 'Bapak Suryadi & Istri',
                'customer_review' => 'Perjalanan keliling Swiss yang sangat nyaman. Kereta panorama Alpen bersih, pemandangan salju abadi memukau, dan hotel sangat memuaskan.',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 5,
            ],
            [
                'title'           => 'Private Family Trip Eksklusif: Petualangan Musim Salju Hokkaido',
                'category'        => 'Jepang',
                'image_path'      => 'banners/images/01M2JJSD71NDGM4MKVCJSZXX3S.jpg',
                'destination'     => 'Hokkaido & Sapporo, Jepang',
                'trip_date'       => 'Desember 2026',
                'customer_name'   => 'Keluarga Besar Bpk. Gunawan',
                'customer_review' => 'Pelayanan private van dan itinerary fleksibel sesuai kenyamanan keluarga besar kami. Anak-anak sangat senang main salju!',
                'rating'          => 5,
                'is_featured'     => false,
                'is_active'       => true,
                'sort_order'      => 6,
            ],
            [
                'title'           => 'Keseruan Menikmati Keindahan Bosphorus Cruise & Hagia Sophia',
                'category'        => 'Turki',
                'image_path'      => 'banners/images/01M2J0A32Z4SVZYH1SCAJRF4XV.webp',
                'destination'     => 'Istanbul, Turki',
                'trip_date'       => 'September 2026',
                'customer_name'   => 'Komunitas Traveler Alumni Jakarta',
                'customer_review' => 'Pemandu lokal berbahasa Indonesia sangat informatif menceritakan sejarah peradaban Islam di Istanbul. Pengalaman spiritual & wisata yang berkesan.',
                'rating'          => 5,
                'is_featured'     => false,
                'is_active'       => true,
                'sort_order'      => 7,
            ],
            [
                'title'           => 'Momen Sunset Mempesona di Santorini & Kepulauan Yunani',
                'category'        => 'Yunani',
                'image_path'      => 'banners/images/01M2JF85ZM9C7S43RKTA6PVHWT.jpeg',
                'destination'     => 'Santorini & Athena, Yunani',
                'trip_date'       => 'Juni 2026',
                'customer_name'   => 'Pasangan Bpk. Dimas & Ibu Clarissa',
                'customer_review' => 'Honeymoon trip terbaik! Pilihan hotel dengan view langsung ke caldera sangat spektakuler. Terima kasih Super Vacation atas pelayanannya.',
                'rating'          => 5,
                'is_featured'     => false,
                'is_active'       => true,
                'sort_order'      => 8,
            ],
            [
                'title'           => 'Eksotisme Pink Beach & Sunset Phinisi di Kepulauan Komodo',
                'category'        => 'Indonesia',
                'image_path'      => 'banners/images/01M2JF85ZM9C7S43RKTA6PVHWT.jpeg',
                'destination'     => 'Labuan Bajo, Nusa Tenggara Timur, Indonesia',
                'trip_date'       => 'Mei 2026',
                'customer_name'   => 'Komunitas Fotografi Nusantara',
                'customer_review' => 'Liveaboard di kapal phinisi sangat mewah dan bersih. Pemandangan pulau Padar dan snorkeling bersama pari manta sungguh magis!',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 9,
            ],
            [
                'title'           => 'Pesona Romantis Menara Eiffel & Keindahan Arsitektur Paris',
                'category'        => 'Prancis',
                'image_path'      => 'banners/images/01M2JFKWDE8QBHTFEXA9N5F6V9.jpeg',
                'destination'     => 'Paris & Versailles, Prancis',
                'trip_date'       => 'April 2026',
                'customer_name'   => 'Ibu Maya Rosalina & Rekan',
                'customer_review' => 'Perjalanan musim semi yang menakjubkan di Paris. Pemandu wisata sangat ramah dan merekomendasikan kafe-kafe lokal yang autentik.',
                'rating'          => 5,
                'is_featured'     => false,
                'is_active'       => true,
                'sort_order'      => 10,
            ],
            [
                'title'           => 'Kemegahan Grand Palace & Wisata Belanja Bangkok',
                'category'        => 'Thailand',
                'image_path'      => 'tours/thumbnails/01M2MKQKC6YW3CHF8MEW7K4H7T.webp',
                'destination'     => 'Bangkok & Pattaya, Thailand',
                'trip_date'       => 'Maret 2026',
                'customer_name'   => 'Rombongan Reuni Angkatan 2005',
                'customer_review' => 'Liburan seru tanpa kendala sama sekali. Transportasi van eksklusif ber-AC dingin dan pilihan restoran dengan makanan halal sangat memuaskan.',
                'rating'          => 5,
                'is_featured'     => false,
                'is_active'       => true,
                'sort_order'      => 11,
            ],
            [
                'title'           => 'Kesejukan Momen Ibadah & Ziarah Bersejarah di Tanah Suci',
                'category'        => 'Arab Saudi',
                'image_path'      => 'banners/images/01M2J0A32Z4SVZYH1SCAJRF4XV.webp',
                'destination'     => 'Makkah & Madinah, Arab Saudi',
                'trip_date'       => 'Januari 2026',
                'customer_name'   => 'Jamaah Umrah Plus TravelGo',
                'customer_review' => 'Bimbingan ibadah yang khusyuk dan fasilitas hotel tepat di depan pelataran Masjidil Haram. Sangat memudahkan jamaah lansia.',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 12,
            ],
            [
                'title'           => 'Momen Tenang di Kuil Fushimi Inari & Hutan Bambu Arashiyama Kyoto',
                'category'        => 'Jepang',
                'image_path'      => 'tours/thumbnails/01M2MK0Q45608Z5G4V6TF1MCX3.webp',
                'destination'     => 'Kyoto & Arashiyama, Jepang',
                'trip_date'       => 'November 2026',
                'customer_name'   => 'Ibu Siska & Komunitas Yoga',
                'customer_review' => 'Jalan pagi menyusuri ribuan gerbang torii merah saat udara musim gugur sejuk sangat menenangkan jiwa.',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 13,
            ],
            [
                'title'           => 'Gemerlap Malam Dotonbori Osaka & Wisata Kuliner Street Food',
                'category'        => 'Jepang',
                'image_path'      => 'banners/images/01M2JJSD71NDGM4MKVCJSZXX3S.jpg',
                'destination'     => 'Osaka & Namba, Jepang',
                'trip_date'       => 'November 2026',
                'customer_name'   => 'Rombongan Young Professional Jakarta',
                'customer_review' => 'Takoyaki asli Osaka terenak yang pernah kami coba! Suasana lampu neon Glico Man malam hari seru sekali.',
                'rating'          => 5,
                'is_featured'     => false,
                'is_active'       => true,
                'sort_order'      => 14,
            ],
            [
                'title'           => 'Keindahan Kolam Air Hangat Alami & Teras Kapur Putih Pamukkale',
                'category'        => 'Turki',
                'image_path'      => 'tours/thumbnails/01M2MKEQ1FPWZ0JP3ZCJ24KZS2.webp',
                'destination'     => 'Pamukkale & Denizli, Turki',
                'trip_date'       => 'September 2026',
                'customer_name'   => 'Keluarga Bpk. Rahmat Santoso',
                'customer_review' => 'Pemandangan terasering putih alami seperti salju dengan air biru toska hangat. Benar-benar keajaiban alam!',
                'rating'          => 5,
                'is_featured'     => false,
                'is_active'       => true,
                'sort_order'      => 15,
            ],
            [
                'title'           => 'Pesona Tradisional Bukchon Hanok & Mengenakan Hanbok di Gyeongbokgung',
                'category'        => 'Korea Selatan',
                'image_path'      => 'tours/thumbnails/01M2MKQKC6YW3CHF8MEW7K4H7T.webp',
                'destination'     => 'Seoul, Korea Selatan',
                'trip_date'       => 'Oktober 2026',
                'customer_name'   => 'Nadia & Clarissa',
                'customer_review' => 'Sewa baju adat Hanbok gratis masuk istana, fotonya bagus-bagus serasa jadi putri di drama Korea!',
                'rating'          => 5,
                'is_featured'     => false,
                'is_active'       => true,
                'sort_order'      => 16,
            ],
            [
                'title'           => 'Sunset Spektakuler di Pantai Haeundae & Gamcheon Culture Village',
                'category'        => 'Korea Selatan',
                'image_path'      => 'banners/images/01M2JF85ZM9C7S43RKTA6PVHWT.jpeg',
                'destination'     => 'Busan, Korea Selatan',
                'trip_date'       => 'Oktober 2026',
                'customer_name'   => 'Grup Travel Family Bandung',
                'customer_review' => 'Rumah warna-warni di perbukitan Gamcheon sangat fotogenik dan angin laut di pantai Haeundae begitu menyegarkan.',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 17,
            ],
            [
                'title'           => 'Pemandangan Futuristik The Bund & Menara Mutiara Shanghai',
                'category'        => 'China',
                'image_path'      => 'tours/thumbnails/01M2MHG1Y5Z5MMB47W58DJBYWX.webp',
                'destination'     => 'Shanghai, China',
                'trip_date'       => 'Oktober 2026',
                'customer_name'   => 'Bpk. Wijaya & Rekan Bisnis',
                'customer_review' => 'Perpaduan gedung kolonial kuno dan pencakar langit modern Shanghai sangat megah dipandang saat malam hari.',
                'rating'          => 5,
                'is_featured'     => false,
                'is_active'       => true,
                'sort_order'      => 18,
            ],
            [
                'title'           => 'Jembatan Kaca Spektakuler di Lembah Hijau Pegunungan Avatar',
                'category'        => 'China',
                'image_path'      => 'banners/images/01M2JFKWDE8QBHTFEXA9N5F6V9.jpeg',
                'destination'     => 'Zhangjiajie & Hunan, China',
                'trip_date'       => 'September 2026',
                'customer_name'   => 'Komunitas Petualang Nusantara',
                'customer_review' => 'Sensasi berjalan di atas jembatan kaca tertinggi dengan jurang ratusan meter di bawah kaki. Adrenalin terpacu!',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 19,
            ],
            [
                'title'           => 'Pesona Puncak Salju Abadi Matterhorn & Keasrian Desa Bebas Polusi Zermatt',
                'category'        => 'Swiss',
                'image_path'      => 'banners/images/01M2JFKWDE8QBHTFEXA9N5F6V9.jpeg',
                'destination'     => 'Zermatt & Matterhorn, Swiss',
                'trip_date'       => 'Juli 2026',
                'customer_name'   => 'Keluarga Bpk. Irwan Santika',
                'customer_review' => 'Udara pegunungan Swiss terbersih di dunia. Menaiki kereta gantung melihat puncak piramida es Matterhorn tak terlupakan seumur hidup.',
                'rating'          => 5,
                'is_featured'     => true,
                'is_active'       => true,
                'sort_order'      => 20,
            ],
        ];

        foreach ($galleries as $gal) {
            Gallery::updateOrCreate(
                ['title' => $gal['title']],
                $gal
            );
        }
    }
}
